### PR TITLE
added package.json

### PR DESCRIPTION
**Pull request by stbaer**
Added package json. This allows the installation via 'npm i ushahidi/jquery-simplepicker'.

### CODE REVIEW

**Comment by shadowhand** [comment]
Can you add instructions for installing with NPM to the README as well?

**Comment by stbaer** [comment]
Done.

**Comment by stbaer** [comment]
@shadowhand - you could also publish to npm, then the installation would be identical to bower (npm install jquery-simplepicker).

**Comment by shadowhand** [comment]
Well, I can't, because I don't manage this repo, but someone could. :)

**Comment by stbaer** [comment]
Ah right, that should have been @ushahidi

**Pull request merged**
